config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root to: "home#index"

  devise_for :users

  resource :establishment, except: [ :destroy ] do
    resources :business_hours, except: [ :destroy ]

    resources :employees
  end

  resolve("Establishment") { [ :establishment ] }
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_establishment

  def index
    @pending_employees = @establishment.pending_employees
  end

  def new
    @pending_employee = @establishment.pending_employees.build
  end

  def create
    @pending_employee = @establishment.pending_employees.build(employees_params)

    if @pending_employee.save
      redirect_to establishment_employees_path(@establishment),
      notice: t("notices.permission_registered")
    else
      flash.now[:alert] =  @pending_employee.errors.full_messages.join(", ")
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_establishment
    @establishment = Establishment.find(params[:format])
  end

  def employees_params
    params.require(:pending_employee).permit(:email, :personal_national_id)
  end
end

app/views/employees/_pending_employee.html.erb
<div>
  <%= t('activerecord.attributes.pending_employee.status') %>
  <%= PendingEmployee.human_enum_name(:status, pending_employee.status ) %>
  <br>
  <%= t('activerecord.attributes.pending_employee.email') %>
  <%= pending_employee.email %>
  <br>
  <%= t('activerecord.attributes.pending_employee.personal_national_id') %>
  <%= pending_employee.personal_national_id %>
</div>

app/views/employees/index.html.erb
<h1>PENDING EMPLOYEES</h1>

<%= link_to "Nova Autorização", new_establishment_employee_path(@establishment) %>

<%= render partial: 'employees/pending_employee', collection: @pending_employees %>

app/views/employees/new.html.erb
<h1>CRIAR PERMISSÃO DE FUNCIONÁRIO</h1>

<%= form_with model: [@establishment, @pending_employee], url: establishment_employees_path(@establishment), method: :post do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :personal_national_id %>
  <%= f.text_field :personal_national_id %>

  <%= f.submit t('activerecord.helpers.pending_employee.allow_registration')%>
<% end %>

<%= link_to t('helpers.cancel'), establishment_employees_path(@establishment) %>