config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root to: "home#index"

  devise_for :users

  resource :establishment, except: [ :destroy ] do
    resources :business_hours, except: [ :destroy ]

    resources :employees
  end

  resolve("Establishment") { [ :establishment ] }
end

app/models/business_hour.rb
class BusinessHour < ApplicationRecord
  belongs_to :establishment

  enum :day_of_week, { sunday: 0, monday: 1, tuesday: 2, wednesday: 3, thursday: 4, friday: 5, saturday: 6 }

  validates :day_of_week, :status, presence: true
  validates :status, inclusion: [ "opened", "closed" ]

  validate :times_must_be_present_when_open
  validate :close_time_must_postdate_open_time

  private

  def close_time_must_postdate_open_time
    return if open_time.blank? || close_time.blank? || status == "closed"

    if open_time >= close_time
      errors.add(:close_time, :postdating)
    end
  end

  def times_must_be_present_when_open
    return unless status == "opened"

    if open_time.blank? || close_time.blank?
      errors.add(:open_time, :time_missing)
    end
  end
end

app/controllers/business_hours_controller.rb
class BusinessHoursController < ApplicationController
  before_action :set_establishment, only: [ :index ]

  skip_before_action :require_registration_steps, only: [ :index, :edit, :update ]

  def index
    @business_hours = @establishment.business_hours
  end

  def edit
    @business_hour = BusinessHour.find(params[:id])
    @establishment = @business_hour.establishment
  end

  def update
    @establishment = Establishment.find(params[:id])
    business_hour_id = params[:format].to_i
    @business_hour = @establishment.business_hours.find { |bh| bh.id == business_hour_id }

    if @business_hour.update(business_hour_params)
      redirect_to establishment_business_hours_path(@establishment.id), notice: "Horário atualizado com sucesso"
    else
      flash.now[:alert] =  @business_hour.errors.full_messages.join(", ")
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_establishment
    @establishment = Establishment.find(params[:format])
  end

  def business_hour_params
    params.require(:business_hour).permit(:day_of_week, :status, :open_time, :close_time)
  end
end

app/views/business_hours/edit.html.erb
<%= t('activerecord.helpers.business_hour.update') %>

<%= form_with model: [@establishment, @business_hour], data: { turbo: false} do |f|%>
  <%= f.hidden_field :day_of_week, value: f.object.day_of_week %>
  <%= f.hidden_field :status, value: 'opened' %>

  <%= t("activerecord.attributes.business_hour.status.#{f.object.status}") %>

  <% if f.object.status == 'opened'%>
    <div>
      <%=
        t('activerecord.helpers.business_hour.current_day_schedule',
        open_time: f.object.open_time.strftime("%H:%M"),
        close_time: f.object.close_time.strftime("%H:%M"))
      %>
    </div>

    <%= f.hidden_field :day_of_week, value: f.object.day_of_week %>
    <%= f.hidden_field :open_time, value: '' %>
    <%= f.hidden_field :close_time, value: '' %>
    <%= f.hidden_field :status, value: 'closed' %>

    <%= f.submit t('activerecord.helpers.business_hour.set_as_closed') %>
  <% end %>

  <div>
    <%= f.label :open_time %>
    <%= f.time_field :open_time, value: '' %>

    <%= f.label :close_time %>
    <%= f.time_field :close_time, value: '' %>
  </div>

  <%= link_to t('helpers.cancel'), establishment_business_hours_path(@establishment) %>
  <%= f.submit %>
<% end %>

app/views/business_hours/index.html.erb
<%= t('activerecord.models.business_hour.other') %>

<% @business_hours.each do |schedule| %>
  <div id=<%= "edit-#{schedule.day_of_week}" %>>
    <%= link_to edit_establishment_business_hour_path(schedule) do %>
      <strong>
        <%= t("activerecord.attributes.business_hour.status.#{schedule.status}") %>
      </strong>
      <br>
      <%= BusinessHour.human_enum_name(:day_of_week, schedule.day_of_week) %>
      <br>
      <% if schedule.status == 'opened' %>
        <%= t("activerecord.attributes.business_hour.open_time") %>
        <%= schedule.open_time.strftime("%H:%M") unless schedule.open_time.nil? %>
        <br>
        <%= t("activerecord.attributes.business_hour.close_time") %>
        <%= schedule.close_time.strftime("%H:%M") unless schedule.close_time.nil? %>
        <br>
      <% end %>
    <% end %>
  </div>
<% end %>